media:
  input: src/media
  output: /media

content:

  - name: pages
    label: Pages
    type: collection
    path: 'src/pages/dynamic'
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Publication date
        type: date
      - name: permalink
        label: Permalink
        type: string
        description: The link path for this site, e.g. "/bio/" makes the site available under "https://<website url>/bio/" The slash / in the end is important, it's not gonna work without for some reason.
      - name: order
        type: number
        label: Navigation order
        description: The links in the navigation will be shown in the order given here. Make sure each site has a different positive number so the ordering works.
      - name: layout
        type: string
        hidden: true
        default: "page" 
      - name: hidden
        label: Hidden
        type: boolean
        description: You can hide a site from the navigation if you activate this. Then it will still be accessible by directly visiting the url of the site.
      - name: body
        label: Body
        type: rich-text
        description: You can embed YouTube videos by adding an new line with only the link to the video and nothing else in it. This will automatically embed the video in the post.

  - name: gigs
    label: Gigs
    type: collection
    path: 'src/gigs'
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Creation date
        type: date
      - name: time
        type: string
        description: Time of the gig, e.g. 18-20
      - name: location
        type: string
        description: Location
      - name: gmaps
        type: string
        required: false
        description: Google Maps link (optional), must be a valid link  
      - name: fblink
        type: string
        required: false
        description: Facebook event link (optional), must be a valid link 
      - name: weblink
        type: string
        required: false
        description: Website event link (optional), must be a valid link 
      - name: body
        label: Description
        type: rich-text
        description: Write a sentence or so with a description and any additional info.

  - name: home
    label: Home page
    path: src/pages/special/home.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        type: string
        hidden: true
        default: "/"
      - name: order
        type: number
        hidden: true
        default: 0
      - name: hidden
        type: boolean
        hidden: true
        default: false     
      - name: layout
        type: string
        hidden: true
        default: "home"   
      - name: body
        label: Body
        type: rich-text
        description: You can embed YouTube videos by adding an new line with only the link to the video and nothing else in it. This will automatically embed the video in the post.

  - name: site
    label: Site settings
    path: src/_data/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: keywords
        label: Website keywords
        type: string
        description: Comma-separated list of keywords for search engines