media:
  input: src/media
  output: /media

content:

  - name: pages
    label: Pages
    type: collection
    path: 'src/pages/dynamic'
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        label: Permalink
        type: string
        description: The link path for this site, e.g. "/bio/" makes the site available under "https://<website url>/bio/" The slash / in the end is important, it's not gonna work without for some reason.
      - name: order
        type: number
        label: Navigation order
        description: The links in the navigation will be shown in the order given here. Make sure each site has a different positive number so the ordering works.
      - name: layout
        type: string
        hidden: true
        default: "page" 
      - name: enableLightbox
        label: Enable Image Gallary
        type: boolean
        description: If you enable this, groups of consecutive pictures are wrapped into a column layout and will open in a media gallery when clicked. This is specifically meant for the "media" page.
      - name: hidden
        label: Hidden
        type: boolean
        description: You can hide a site from the navigation if you activate this. Then it will still be accessible by directly visiting the url of the site.
      - name: body
        label: Body
        type: rich-text
        description: You can embed YouTube videos by adding an new line with only the link to the video and nothing else in it. This will automatically embed the video in the post.
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        search: ''
        sort: order
        order: asc

  - name: gigs
    label: Gigs
    type: collection
    path: 'src/gigs'
    icon: guitar
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: time
        type: string
        label: Time
        description: Time of the gig, e.g. 18-20
      - name: location
        type: string
        label: Location
      - name: gmaps
        label: Google Maps link
        type: string
        required: false
        description: Optional, must be a valid link  
      - name: fblink
        label: Facebook event link
        type: string
        required: false
        description: Optional, must be a valid link 
      - name: weblink
        label: Website event link
        type: string
        required: false
        description: Optional, must be a valid link 
      - name: body
        label: Description
        type: rich-text
        description: Write a sentence or so with a description and any additional info.
    view:
      fields: [ title, date, location ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: asc

  - name: home
    label: Home page
    path: src/pages/special/home.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: permalink
        type: string
        hidden: true
        default: "/"
      - name: order
        type: number
        hidden: true
        default: 0
      - name: hidden
        type: boolean
        hidden: true
        default: false     
      - name: layout
        type: string
        hidden: true
        default: "home"   
      - name: body
        label: Body
        type: rich-text
        description: You can embed YouTube videos by adding an new line with only the link to the video and nothing else in it. This will automatically embed the video in the post.

  - name: site
    label: Site Configuration
    path: src/_data/site.json
    type: file
    icon: cog
    fields:
      - name: title
        label: Website title
        type: string
        description: The title of the site, shown on search engine results and in the browser tab title
      - name: description
        label: Website description
        type: string
        description: Description of the site, used mainly for search engines
      - name: keywords
        label: Website keywords
        type: string
        description: Comma-separated list of keywords for search engines
      - name: slogan
        label: Slogan
        type: string
        description: The slogan that is shown on the home page. Be careful to change this as the current layout is somewhat relying on a certain length of this slogan (e.g. a too long slogan will probably break the layout of the home page).
      - name: url
        type: string
        hidden: true
        description: The root URL of the website
      - name: baseUrl
        type: string
        hidden: true
        description: The path prefix, e.g. /friction-website/ if the website is hosted under <url>/friction-website/